### ISSUE TITLE
Can't resolve 'react/jsx-runtime' in storybook-xstate-addon dist

### ISSUE THREAD

**Issue by richpjames** [SimeonC/storybook-xstate-addon#27]
On attempting to run storybook I am presented with the following error after installing this addon for the first time: 

```
ERROR in ./node_modules/storybook-xstate-addon/dist/preset/manager.js
[storybook] Module not found: Error: Can't resolve 'react/jsx-runtime' in '\node_modules\storybook-xstate-addon\dist\preset'
```

I am using react and react-dom version 16.2.0 and @storybook/react 6.2.9

Apologies if this an issue with my config and not the addon itself but I thought it was worth raising as this addon looks amazing and I really want to be able to use it

**Comment by SimeonC** [comment]
Hey, sorry for the issue report. I think this is related to #26 but I haven't had time to fix it yet.

**Comment by richpjames** [comment]
I think you're right, if I make this package's peer dependencies: 
 ``` "react": "16.12.0 || 17.0.0",
     "react-dom": "16.12.0 || 17.0.0" ```
as suggested in #26 then the error goes away - feel free to close this issue.

**Comment by SimeonC** [comment]
Try the newly released v1.1.4 I moved all my deps to peer and dev so this should be resolved.

**Comment by richpjames** [comment]
Thanks for doing this @SimeonC. I think the change you made is the right thing to do but unfortunately I can't update as we are using v16.12 of React

**Comment by SimeonC** [comment]
Ahh, my bad 🤦  I meant to change this to match storybooks react peer deps which are `"^16.8.0 || ^17.0.0"` but completely forgot. New version v1.1.5 should allow you to use this with v16.12 (There shouldn't be any issues with swapping react 16 and 16 as far as I've seen so far)

**Comment by richpjames** [comment]
Ah awesome, thanks - I can install it again!
However when running Storybook I get the same error that I got to begin with
```  ERROR in ./node_modules/storybook-xstate-addon/dist/preset/manager.js
Module not found: Error: Can't resolve 'react/jsx-runtime' in '..\node_modules\storybook-xstate-addon\dist\preset' ```
