### ISSUE TITLE
support new stately viz 

### ISSUE THREAD

**Issue by epikhighs** [SimeonC/storybook-xstate-addon#31]
Hi, there's a new [visualizer released](https://stately.ai/viz) ([link to repo](https://github.com/statelyai/xstate-viz#features))  and it looks the `url` param that gets passed into the xstate inspector  just needs to be configurable from `storybook-xstate-addon`

```Inspect machines by setting url: 'https://stately.ai/viz?inspect' in @xstate/inspect```

Can this be supported?

**Comment by SimeonC** [comment]
Yea, we can definitely do this. It's on my list of things to do with the new viz but just haven't had time to look into yet.

**Comment by SimeonC** [comment]
This should be supported in 1.1.6 now thanks to @maximblack
