### ISSUE TITLE
Feature Request: Compatibility with vite-storybook-builder

### ISSUE THREAD

**Issue by justrhysism** [SimeonC/storybook-xstate-addon#37]
Whatever the target dist build is doesn't appear to work with Vite at the moment :( 

`exports is not defined`

![image](https://user-images.githubusercontent.com/1326759/159213226-445988bd-3d2f-4d8e-8750-26298bab6759.png)

**Comment by SimeonC** [comment]
Hmm, looks like Vite is expecting `esm` output (currently only have `es5` compatible output). Haven't had any time to look at vite yet, can you tell vite that storybook-xstate-addon is a es5 package instead of es6?

**Comment by SimeonC** [comment]
@justrhysism I just released a new version which has the ESM build (as per the new setup from storybook/addon-kit). I think it may fix the support for vite - if not please re-open this issue.
