### ISSUE TITLE
v7 Support

### ISSUE THREAD

**Issue by SimeonC** [SimeonC/storybook-xstate-addon#52]
**Describe the bug**
Need to upgrade versions and major bump to support storybook v7
![CleanShot 2023-01-25 at 15 28 29](https://user-images.githubusercontent.com/1085899/214495686-c7450851-23c5-4a0e-a513-a4d8e22162f5.png)

**To Reproduce**
* Storybook Version: v7
* This Plugin Version: any

**Expected behavior**
It works in v7 without erroring

**Comment by HakimCh** [comment]
Hello @SimeonC,

I tried the second case, and i cannot reproduce this error with the latest version of Storybook v7.0.7 on a react & vite project.

Test repo : [storybook-v7-xstate-addon](https://github.com/HakimCh/storybook-v7-xstate-addon/tree/main)

**Comment by SimeonC** [comment]
Thanks for confirming, I'll close this then and reopen if we get any other issues with v7
