### ISSUE TITLE
Storybook demo not working

### ISSUE THREAD

**Issue by SimeonC** [SimeonC/storybook-xstate-addon#6]
Deployed but not working in browser (Edge, FF, windows)

https://simeonc.github.io/storybook-xstate-addon

**Comment by SimeonC** [comment]
Looks like this is due to https://github.com/davidkpiano/xstate/blob/master/packages/core/src/environment.ts#L1.

This line disables all `devTools` in a "production" run, meaning build-storybook will not work.

**Comment by kaelig** [comment]
👋🏻 I'm not able to display the addon in the demo, is that normal?

**Comment by SimeonC** [comment]
Thanks for pointing that out, I thought I'd fixed it but missed the lib build step in the github actions! Looks like it should be fixed now.
